-- ============================================================
-- Migration 011: Normalize technician offers per request
-- ============================================================

CREATE TABLE IF NOT EXISTS public.request_offers (
  offer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id BIGINT NOT NULL REFERENCES public.request(request_id) ON DELETE CASCADE,
  technician_id BIGINT NOT NULL REFERENCES public.technician(technician_id) ON DELETE CASCADE,
  offered_price NUMERIC(12,2) NOT NULL CHECK (offered_price > 0),
  customer_counter_price NUMERIC(12,2),
  fixer_message TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (request_id, technician_id)
);

CREATE INDEX IF NOT EXISTS idx_request_offers_request_id
  ON public.request_offers (request_id);

CREATE INDEX IF NOT EXISTS idx_request_offers_technician_id
  ON public.request_offers (technician_id);

CREATE INDEX IF NOT EXISTS idx_request_offers_status
  ON public.request_offers (status);

CREATE OR REPLACE FUNCTION public.touch_request_offers_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_request_offers_updated_at ON public.request_offers;

CREATE TRIGGER trg_touch_request_offers_updated_at
BEFORE UPDATE ON public.request_offers
FOR EACH ROW
EXECUTE FUNCTION public.touch_request_offers_updated_at();

ALTER TABLE public.request_offers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS request_offers_auth_select ON public.request_offers;
DROP POLICY IF EXISTS request_offers_technician_insert ON public.request_offers;
DROP POLICY IF EXISTS request_offers_technician_update ON public.request_offers;
DROP POLICY IF EXISTS request_offers_customer_update_counter ON public.request_offers;
DROP POLICY IF EXISTS request_offers_admin_all ON public.request_offers;

CREATE POLICY request_offers_auth_select
  ON public.request_offers
  FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY request_offers_technician_insert
  ON public.request_offers
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.technician t
      WHERE t.technician_id = request_offers.technician_id
        AND lower(t.email) = lower(auth.jwt()->>'email')
    )
  );

CREATE POLICY request_offers_technician_update
  ON public.request_offers
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1
      FROM public.technician t
      WHERE t.technician_id = request_offers.technician_id
        AND lower(t.email) = lower(auth.jwt()->>'email')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.technician t
      WHERE t.technician_id = request_offers.technician_id
        AND lower(t.email) = lower(auth.jwt()->>'email')
    )
  );

CREATE POLICY request_offers_customer_update_counter
  ON public.request_offers
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1
      FROM public.request r
      JOIN public.users u ON u.user_id = r.user_id
      WHERE r.request_id = request_offers.request_id
        AND lower(u.email) = lower(auth.jwt()->>'email')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.request r
      JOIN public.users u ON u.user_id = r.user_id
      WHERE r.request_id = request_offers.request_id
        AND lower(u.email) = lower(auth.jwt()->>'email')
    )
  );

CREATE POLICY request_offers_admin_all
  ON public.request_offers
  FOR ALL
  USING ((auth.jwt()->'user_metadata'->>'role') = 'admin')
  WITH CHECK ((auth.jwt()->'user_metadata'->>'role') = 'admin');

REVOKE ALL ON public.request_offers FROM anon;
GRANT SELECT, INSERT, UPDATE ON public.request_offers TO authenticated;

DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.request_offers;
  EXCEPTION
    WHEN duplicate_object THEN NULL;
  END;
END $$;

NOTIFY pgrst, 'reload schema';
